// export.go defines `envlock export --format <fmt>`.
// Output goes to stdout so it can be piped into other tools.
// All formats expose plaintext secrets — handle the output with care.
package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

const (
	fmtShell         = "shell"
	fmtDocker        = "docker"
	fmtJSON          = "json"
	fmtDotenv        = "dotenv"
	fmtGithubActions = "github-actions"
)

var exportFormatFlag string

var exportCmd = &cobra.Command{
	Use:   "export",
	Short: "Export secrets to stdout in various formats",
	Long: fmt.Sprintf(`Decrypt the vault and print secrets to stdout in the requested format.

⚠  Output contains plaintext secrets. Do not log, commit, or display publicly.

Supported formats:
  %-18s  eval $(envlock export --format shell)
  %-18s  docker run $(envlock export --format docker) myimage
  %-18s  envlock export --format json | jq '.DB_URL'
  %-18s  envlock export --format dotenv > .env.production
  %-18s  Append to $GITHUB_ENV in CI`, fmtShell, fmtDocker, fmtJSON, fmtDotenv, fmtGithubActions),
	Args:    cobra.NoArgs,
	RunE:    runExport,
	Example: "  envlock export --format shell\n  envlock export --format json | jq\n  envlock export --format docker",
}

func init() {
	exportCmd.Flags().StringVarP(&exportFormatFlag, "format", "f", fmtDotenv,
		fmt.Sprintf("output format: %s|%s|%s|%s|%s",
			fmtShell, fmtDocker, fmtJSON, fmtDotenv, fmtGithubActions))
	rootCmd.AddCommand(exportCmd)
}

func runExport(cmd *cobra.Command, args []string) error {
	ctx, err := loadVaultCtx()
	if err != nil {
		return err
	}

	keys := ctx.vault.List()
	if len(keys) == 0 {
		return fmt.Errorf("vault is empty. Add secrets with: envlock add KEY=value")
	}

	// Warn on stderr so it doesn't pollute the piped stdout.
	color.New(color.FgYellow).Fprintln(os.Stderr,
		"⚠  Output contains plaintext secrets — pipe carefully.")

	switch exportFormatFlag {
	case fmtShell:
		return exportShell(ctx, keys)
	case fmtDocker:
		return exportDocker(ctx, keys)
	case fmtJSON:
		return exportJSON(ctx, keys)
	case fmtDotenv:
		return exportDotenv(ctx, keys)
	case fmtGithubActions:
		return exportGithubActions(ctx, keys)
	default:
		return fmt.Errorf("unknown format %q. Choose: %s|%s|%s|%s|%s",
			exportFormatFlag, fmtShell, fmtDocker, fmtJSON, fmtDotenv, fmtGithubActions)
	}
}

// exportShell outputs: export KEY='value'
// Suitable for: eval $(envlock export --format shell)
func exportShell(ctx *vaultCtx, keys []string) error {
	for _, k := range keys {
		v, _ := ctx.vault.Get(k)
		fmt.Printf("export %s=%s\n", k, singleQuote(v))
	}
	return nil
}

// exportDocker outputs: --env KEY=value (one flag pair per word, space-separated)
// Suitable for: docker run $(envlock export --format docker) myimage
func exportDocker(ctx *vaultCtx, keys []string) error {
	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		v, _ := ctx.vault.Get(k)
		parts = append(parts, fmt.Sprintf("--env %s=%s", k, shellQuote(v)))
	}
	fmt.Println(strings.Join(parts, " "))
	return nil
}

// exportJSON outputs a pretty-printed JSON object.
// Suitable for: envlock export --format json | jq '.KEY'
func exportJSON(ctx *vaultCtx, keys []string) error {
	m := make(map[string]string, len(keys))
	for _, k := range keys {
		v, _ := ctx.vault.Get(k)
		m[k] = v
	}
	enc, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return fmt.Errorf("encoding JSON: %w", err)
	}
	fmt.Println(string(enc))
	return nil
}

// exportDotenv outputs: KEY=value (standard .env format with quoting)
// Suitable for: envlock export --format dotenv > .env.production
func exportDotenv(ctx *vaultCtx, keys []string) error {
	fmt.Println("# Generated by envlock — do not commit")
	for _, k := range keys {
		v, _ := ctx.vault.Get(k)
		fmt.Printf("%s=%s\n", k, dotenvQuote(v))
	}
	return nil
}

// exportGithubActions writes to the $GITHUB_ENV append format:
//
//	KEY=simple_value
//	MULTILINE_KEY<<_ENVLOCK_EOF
//	line one
//	line two
//	_ENVLOCK_EOF
//
// Suitable for: envlock export --format github-actions >> $GITHUB_ENV
func exportGithubActions(ctx *vaultCtx, keys []string) error {
	const delimiter = "_ENVLOCK_EOF"
	for _, k := range keys {
		v, _ := ctx.vault.Get(k)
		if strings.Contains(v, "\n") {
			fmt.Printf("%s<<%s\n%s\n%s\n", k, delimiter, v, delimiter)
		} else {
			fmt.Printf("%s=%s\n", k, v)
		}
	}
	return nil
}

// ── quoting helpers ───────────────────────────────────────────────────────────

// singleQuote wraps v in POSIX single quotes, escaping any embedded ' by
// ending the quote, inserting \', and reopening.
func singleQuote(v string) string {
	return "'" + strings.ReplaceAll(v, "'", `'\''`) + "'"
}

// shellQuote returns v wrapped in double quotes when it contains characters
// that would be split by the shell, otherwise returns v unquoted.
func shellQuote(v string) string {
	needsQ := false
	for _, c := range v {
		if c == ' ' || c == '\t' || c == '"' || c == '\'' || c == '\\' ||
			c == '$' || c == '`' || c == '!' || c == '\n' {
			needsQ = true
			break
		}
	}
	if !needsQ {
		return v
	}
	v = strings.ReplaceAll(v, `\`, `\\`)
	v = strings.ReplaceAll(v, `"`, `\"`)
	v = strings.ReplaceAll(v, `$`, `\$`)
	v = strings.ReplaceAll(v, "`", "\\`")
	return `"` + v + `"`
}

// dotenvQuote applies the same quoting as env.quoteEnvValue but inline here
// to keep the export package self-contained.
func dotenvQuote(v string) string {
	needsQ := v == ""
	if !needsQ {
		for _, c := range v {
			if c <= ' ' || c == '#' || c == '"' || c == '\'' || c == '\\' || c == '$' || c == '`' {
				needsQ = true
				break
			}
		}
	}
	if !needsQ {
		return v
	}
	var sb strings.Builder
	sb.WriteByte('"')
	for _, c := range v {
		switch c {
		case '"':
			sb.WriteString(`\"`)
		case '\\':
			sb.WriteString(`\\`)
		case '\n':
			sb.WriteString(`\n`)
		case '\t':
			sb.WriteString(`\t`)
		default:
			sb.WriteRune(c)
		}
	}
	sb.WriteByte('"')
	return sb.String()
}
