// Package env parses and writes .env files in the common KEY=VALUE format.
// It handles unquoted, single-quoted, and double-quoted values, inline
// comments, blank lines, and multi-line double-quoted values.
package env

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"
)

const (
	envFileHeader  = "# Generated by envlock — do not edit manually\n# Run 'envlock pull' to refresh from the vault\n\n"
	envFilePerms   = 0o600 // secrets file: owner read/write only
)

// ParseEnvFile reads a .env file at path and returns a map of key→value pairs.
//
// Supported syntax:
//   - KEY=value              unquoted (inline # comments stripped)
//   - KEY="value"            double-quoted (escape sequences: \n \t \r \" \\)
//   - KEY='value'            single-quoted (literal; no escape handling)
//   - KEY="multi\nline"      escaped newlines in double-quoted
//   - export KEY=value       bash export prefix is ignored
//   - # comment              full-line comments are skipped
func ParseEnvFile(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}
	return parseEnvBytes(data)
}

// WriteEnvFile writes secrets to path in .env format, sorted alphabetically.
// Values that require quoting (spaces, special characters) are double-quoted.
// The file is written with mode 0600.
func WriteEnvFile(path string, secrets map[string]string) error {
	keys := sortedKeys(secrets)

	var sb strings.Builder
	sb.WriteString(envFileHeader)
	for _, k := range keys {
		sb.WriteString(k)
		sb.WriteByte('=')
		sb.WriteString(quoteEnvValue(secrets[k]))
		sb.WriteByte('\n')
	}

	if err := os.WriteFile(path, []byte(sb.String()), envFilePerms); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// parseEnvBytes is the core parser — operates on a raw byte slice so it can
// be called from tests without hitting the filesystem.
func parseEnvBytes(data []byte) (map[string]string, error) {
	result := make(map[string]string)

	// Normalise line endings.
	src := strings.ReplaceAll(string(data), "\r\n", "\n")
	lines := strings.Split(src, "\n")

	i := 0
	for i < len(lines) {
		line := lines[i]
		i++

		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		// Drop optional 'export ' prefix for bash-compat files.
		trimmed = strings.TrimPrefix(trimmed, "export ")
		trimmed = strings.TrimSpace(trimmed)

		eqIdx := strings.IndexByte(trimmed, '=')
		if eqIdx <= 0 {
			continue // skip lines with no '=' or empty key
		}

		key := strings.TrimSpace(trimmed[:eqIdx])
		rawVal := strings.TrimLeft(trimmed[eqIdx+1:], " \t")

		val, consumed, err := extractValue(rawVal, lines, i)
		if err != nil {
			return nil, fmt.Errorf("key %s (line %d): %w", key, i, err)
		}
		i += consumed // advance past any extra lines consumed by multi-line value

		result[key] = val
	}
	return result, nil
}

// extractValue parses the raw right-hand side of a KEY= assignment.
// consumed reports how many additional lines from rest were consumed (for
// multi-line double-quoted values).
func extractValue(raw string, rest []string, nextLine int) (value string, consumed int, err error) {
	if raw == "" {
		return "", 0, nil
	}

	switch raw[0] {
	case '\'':
		// Single-quoted: literal content, no escape handling.
		end := strings.IndexByte(raw[1:], '\'')
		if end < 0 {
			return "", 0, fmt.Errorf("unterminated single-quoted value")
		}
		return raw[1 : end+1], 0, nil

	case '"':
		// Double-quoted: escape sequences and optional multi-line continuation.
		var sb strings.Builder
		j := 1 // position within current line, starting after opening '"'
		cur := raw
		extra := 0

		for {
			if j >= len(cur) {
				// Value spans into the next line.
				if nextLine+extra >= len(rest) {
					return "", 0, fmt.Errorf("unterminated double-quoted value")
				}
				sb.WriteByte('\n')
				cur = rest[nextLine+extra]
				extra++
				j = 0
				continue
			}
			c := cur[j]
			if c == '"' {
				break // closing quote found
			}
			if c == '\\' && j+1 < len(cur) {
				j++
				switch cur[j] {
				case 'n':
					sb.WriteByte('\n')
				case 't':
					sb.WriteByte('\t')
				case 'r':
					sb.WriteByte('\r')
				case '"':
					sb.WriteByte('"')
				case '\\':
					sb.WriteByte('\\')
				default:
					sb.WriteByte('\\')
					sb.WriteByte(cur[j])
				}
			} else {
				sb.WriteByte(c)
			}
			j++
		}
		return sb.String(), extra, nil

	default:
		// Unquoted: strip inline comment and trailing whitespace.
		if idx := strings.Index(raw, " #"); idx >= 0 {
			raw = raw[:idx]
		}
		return strings.TrimRightFunc(raw, unicode.IsSpace), 0, nil
	}
}

// quoteEnvValue wraps v in double quotes if it contains characters that would
// break an unquoted .env assignment.
func quoteEnvValue(v string) string {
	if !needsQuoting(v) {
		return v
	}
	var sb strings.Builder
	sb.WriteByte('"')
	for _, c := range v {
		switch c {
		case '"':
			sb.WriteString(`\"`)
		case '\\':
			sb.WriteString(`\\`)
		case '\n':
			sb.WriteString(`\n`)
		case '\t':
			sb.WriteString(`\t`)
		case '\r':
			sb.WriteString(`\r`)
		default:
			sb.WriteRune(c)
		}
	}
	sb.WriteByte('"')
	return sb.String()
}

// needsQuoting reports whether v must be double-quoted in a .env file.
func needsQuoting(v string) bool {
	if v == "" {
		return true // empty values must be quoted: KEY=""
	}
	for _, c := range v {
		if c <= ' ' || c == '#' || c == '"' || c == '\'' || c == '\\' || c == '$' || c == '`' || c == '!' {
			return true
		}
	}
	return false
}

// sortedKeys returns the keys of m sorted alphabetically.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
